# Generated by Django 5.2.11 on 2026-03-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('FARM', 'Farm Staff'), ('WAREHOUSE', 'Warehouse Staff'), ('DELIVERY', 'Delivery Person'), ('DRIVER', 'Driver')], max_length=20),
        ),
    ]
