# Generated by Django 5.2.11 on 2026-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='route_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
