# Generated by Django 5.2.11 on 2026-03-24 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FarmDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WashingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date'], name='bottles_ale_date_b4600b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BottlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('delivery_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bottles.deliveryassignment')),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
            ],
            options={
                'ordering': ['bottle_type'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deliveries', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bottles.deliveryassignment')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assignment__date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('collected', models.PositiveIntegerField(default=0)),
                ('breakage', models.PositiveIntegerField(default=0)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bottles.deliveryentry')),
            ],
            options={
                'ordering': ['bottle_type'],
            },
        ),
        migrations.CreateModel(
            name='FarmDailyEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to_warehouse', models.PositiveIntegerField(default=0)),
                ('empty_received_from_warehouse', models.PositiveIntegerField(default=0)),
                ('empty_breakage', models.PositiveIntegerField(default=0)),
                ('breakage_reason', models.CharField(blank=True, max_length=100)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
                ('farm_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.farmdailyentry')),
            ],
        ),
        migrations.CreateModel(
            name='VanMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VanMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_sent_to_farm', models.PositiveIntegerField(default=0)),
                ('filled_received_from_farm', models.PositiveIntegerField(default=0)),
                ('breakage', models.PositiveIntegerField(default=0)),
                ('breakage_reason', models.CharField(blank=True, choices=[('TRANSPORT', 'Transport Damage'), ('HANDLING', 'Handling Mistake'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
                ('van_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bottles.vanmovement')),
            ],
            options={
                'ordering': ['bottle_type'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseDailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'entry_type')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseDailyEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from_farm', models.PositiveIntegerField(default=0)),
                ('empty_received_from_delivery', models.PositiveIntegerField(default=0)),
                ('empty_sent_to_farm', models.PositiveIntegerField(default=0)),
                ('warehouse_breakage', models.PositiveIntegerField(default=0)),
                ('breakage_reason', models.CharField(blank=True, max_length=50)),
                ('breakage_approved', models.BooleanField(default=False)),
                ('filled_sent_to_delivery', models.PositiveIntegerField(default=0)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
                ('warehouse_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.warehousedailyentry')),
            ],
        ),
        migrations.CreateModel(
            name='WashingCycleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty_sent_to_wash', models.PositiveIntegerField(default=0)),
                ('ready_after_wash', models.PositiveIntegerField(default=0)),
                ('washing_breakage', models.PositiveIntegerField(default=0)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
                ('washing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bottles.washingcycle')),
            ],
            options={
                'ordering': ['bottle_type'],
            },
        ),
        migrations.CreateModel(
            name='DailyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='bottles_dai_date_a2c3a7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['date'], name='bottles_del_date_012847_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryassignment',
            unique_together={('delivery_user', 'date')},
        ),
        migrations.AddIndex(
            model_name='deliveryassignmentitem',
            index=models.Index(fields=['assignment'], name='bottles_del_assignm_de0ed8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryassignmentitem',
            unique_together={('assignment', 'bottle_type')},
        ),
        migrations.AddIndex(
            model_name='deliveryentry',
            index=models.Index(fields=['status'], name='bottles_del_status_a6e553_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryentryitem',
            index=models.Index(fields=['entry'], name='bottles_del_entry_i_52321f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryentryitem',
            unique_together={('entry', 'bottle_type')},
        ),
        migrations.AlterUniqueTogether(
            name='farmdailyentryitem',
            unique_together={('farm_entry', 'bottle_type')},
        ),
        migrations.AddIndex(
            model_name='vanmovement',
            index=models.Index(fields=['date'], name='bottles_van_date_b1ea5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vanmovement',
            unique_together={('date', 'driver')},
        ),
        migrations.AddIndex(
            model_name='vanmovementitem',
            index=models.Index(fields=['van_movement'], name='bottles_van_van_mov_4b7fb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vanmovementitem',
            unique_together={('van_movement', 'bottle_type')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousedailyentryitem',
            unique_together={('warehouse_entry', 'bottle_type')},
        ),
        migrations.AddIndex(
            model_name='washingcycleitem',
            index=models.Index(fields=['washing'], name='bottles_was_washing_735a43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='washingcycleitem',
            unique_together={('washing', 'bottle_type')},
        ),
    ]
