# Generated by Django 5.2.11 on 2026-03-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('farm_stock', models.IntegerField(default=0)),
                ('warehouse_stock', models.IntegerField(default=0)),
                ('customer_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bottles.bottletype')),
            ],
        ),
    ]
